// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjJJmhNCTIAKT3SPHi7ZDObfXgazHKfPg',
    appId: '1:1048516701393:web:035dbc93aa581fdf8d69f0',
    messagingSenderId: '1048516701393',
    projectId: 'testing-b3694',
    authDomain: 'testing-b3694.firebaseapp.com',
    storageBucket: 'testing-b3694.firebasestorage.app',
    measurementId: 'G-NRY7F6M5FX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH1WISlWji9wraKmA4W8GN6h4sAZWgrxU',
    appId: '1:1048516701393:android:f9b542dd9fc2bb588d69f0',
    messagingSenderId: '1048516701393',
    projectId: 'testing-b3694',
    storageBucket: 'testing-b3694.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz4Sa4fDxRki20cklhZ0w890C7KHbkfYo',
    appId: '1:1048516701393:ios:c23705d0a0fa06348d69f0',
    messagingSenderId: '1048516701393',
    projectId: 'testing-b3694',
    storageBucket: 'testing-b3694.firebasestorage.app',
    iosBundleId: 'com.example.ibaCourse2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz4Sa4fDxRki20cklhZ0w890C7KHbkfYo',
    appId: '1:1048516701393:ios:c23705d0a0fa06348d69f0',
    messagingSenderId: '1048516701393',
    projectId: 'testing-b3694',
    storageBucket: 'testing-b3694.firebasestorage.app',
    iosBundleId: 'com.example.ibaCourse2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjJJmhNCTIAKT3SPHi7ZDObfXgazHKfPg',
    appId: '1:1048516701393:web:09fe400eef9175598d69f0',
    messagingSenderId: '1048516701393',
    projectId: 'testing-b3694',
    authDomain: 'testing-b3694.firebaseapp.com',
    storageBucket: 'testing-b3694.firebasestorage.app',
    measurementId: 'G-XXJGX6ZLBZ',
  );
}
